package agenttools

type Descriptor struct {
	Name             string   `json:"name"`
	Title            string   `json:"title"`
	Description      string   `json:"description"`
	Surface          string   `json:"surface"`
	Risk             string   `json:"risk"`
	RequiresApproval bool     `json:"requiresApproval"`
	Inputs           []string `json:"inputs"`
}

func Registry() []Descriptor {
	return []Descriptor{
		{
			Name:             "workspace.preview",
			Title:            "Preview workspace file",
			Description:      "Read a bounded preview for a file inside the approved workspace root.",
			Surface:          "Code Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath"},
		},
		{
			Name:             "workspace.context",
			Title:            "Read context pack",
			Description:      "Build a bounded multi-file context pack from workspace files, folders, or the project root.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPaths"},
		},
		{
			Name:             "git.diff",
			Title:            "Read Git diff",
			Description:      "Read bounded git status plus staged and unstaged diffs for the workspace or one file.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath"},
		},
		{
			Name:             "git.changedFiles",
			Title:            "Read changed files",
			Description:      "Read changed-file status plus bounded previews for current Git working tree files.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"maxFiles", "includeContent"},
		},
		{
			Name:             "git.history",
			Title:            "Read Git history",
			Description:      "Read bounded commit history for the repository or a single workspace file.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath", "limit"},
		},
		{
			Name:             "git.blame",
			Title:            "Read Git blame",
			Description:      "Read bounded line attribution for one workspace file or line range.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath", "startLine", "endLine"},
		},
		{
			Name:             "workspace.problems",
			Title:            "Scan workspace problems",
			Description:      "Run lightweight read-only diagnostics for markers, merge conflicts, and invalid JSON.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"maxResults"},
		},
		{
			Name:             "workspace.tasks",
			Title:            "List workspace tasks",
			Description:      "List discovered npm scripts, Go tests, and Docker Compose config checks.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{},
		},
		{
			Name:             "workspace.task.run",
			Title:            "Run workspace task",
			Description:      "Run a re-discovered workspace task through the safe task runner with capped output and an artifact.",
			Surface:          "Workbench",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"taskId"},
		},
		{
			Name:             "workspace.write",
			Title:            "Write text file",
			Description:      "Create or update a text/code file through diff preview and modal approval.",
			Surface:          "Code Studio",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"relPath", "content"},
		},
		{
			Name:             "workspace.writeBinary",
			Title:            "Write binary file",
			Description:      "Create or update a binary file from base64 bytes through size/hash preview and modal approval.",
			Surface:          "Code Studio",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"relPath", "base64Content", "contentType"},
		},
		{
			Name:             "workspace.patch",
			Title:            "Apply unified patch",
			Description:      "Apply a unified diff across one or more text/code files after exact-match preview and approval.",
			Surface:          "Workbench",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"patch"},
		},
		{
			Name:             "workspace.copy",
			Title:            "Copy file",
			Description:      "Copy one workspace file to a new path after validation and approval.",
			Surface:          "Workbench",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"sourceRelPath", "targetRelPath"},
		},
		{
			Name:             "workspace.move",
			Title:            "Move or rename file",
			Description:      "Move or rename one workspace file after validation and approval.",
			Surface:          "Workbench",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"sourceRelPath", "targetRelPath"},
		},
		{
			Name:             "workspace.delete",
			Title:            "Delete file",
			Description:      "Delete one workspace file after validation and approval.",
			Surface:          "Workbench",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"relPath"},
		},
		{
			Name:             "workspace.rollback.list",
			Title:            "List file rollbacks",
			Description:      "List rollback snapshots created before approved workspace file mutations.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{},
		},
		{
			Name:             "workspace.rollback.apply",
			Title:            "Apply file rollback",
			Description:      "Restore or remove workspace files from a rollback snapshot after approval.",
			Surface:          "Workbench",
			Risk:             "high",
			RequiresApproval: true,
			Inputs:           []string{"id"},
		},
		{
			Name:             "dataset.query",
			Title:            "Query CSV dataset",
			Description:      "Run a bounded CSV query with text, column, comparison, order, and limit clauses.",
			Surface:          "Data Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath", "query"},
		},
		{
			Name:             "dataset.profile",
			Title:            "Profile dataset",
			Description:      "Create or refresh a bounded metadata profile for CSV, TSV, JSON, NDJSON, XLSX, Parquet, or log files.",
			Surface:          "Data Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath"},
		},
		{
			Name:             "dataset.sql",
			Title:            "Query dataset SQL",
			Description:      "Run a read-only SELECT query against a workspace dataset using DuckDB when available with a bounded fallback.",
			Surface:          "Data Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath", "sql"},
		},
		{
			Name:             "sqlite.inspect",
			Title:            "Inspect SQLite database",
			Description:      "Read schema, row counts, indexes, relationships, and samples from a workspace SQLite database in read-only mode.",
			Surface:          "Data Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath"},
		},
		{
			Name:             "sqlite.query",
			Title:            "Query SQLite database",
			Description:      "Run a bounded read-only SELECT or WITH query against a workspace SQLite database.",
			Surface:          "Data Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath", "sql", "resultLimit", "timeoutSeconds"},
		},
		{
			Name:             "document.set",
			Title:            "Read document set",
			Description:      "Read bounded text context from Markdown, TXT, PDF, DOCX, HTML, and XML files or folders.",
			Surface:          "Workbench",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPaths", "maxFiles"},
		},
		{
			Name:             "artifact.create",
			Title:            "Create artifact",
			Description:      "Create deterministic reports, summaries, charts, or query exports under .nexusdesk/artifacts.",
			Surface:          "Artifact Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"sourcePath", "kind"},
		},
		{
			Name:             "artifact.list",
			Title:            "List artifacts",
			Description:      "List generated artifacts with kind, source, summary, and model metadata.",
			Surface:          "Artifact Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{},
		},
		{
			Name:             "artifact.read",
			Title:            "Read artifact",
			Description:      "Read a bounded artifact preview plus sidecar metadata.",
			Surface:          "Artifact Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath"},
		},
		{
			Name:             "artifact.lineage",
			Title:            "Read artifact lineage",
			Description:      "Read the current artifact/source/chat/tool relationship graph as bounded context.",
			Surface:          "Artifact Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{},
		},
		{
			Name:             "web.fetch",
			Title:            "Fetch web page",
			Description:      "Fetch one approved HTTP(S) text-like URL with redirect, size, content-type, local-network, and optional domain allow-list guards.",
			Surface:          "Workbench",
			Risk:             "medium",
			RequiresApproval: true,
			Inputs:           []string{"url", "allowedDomains", "allowLocal", "maxBytes"},
		},
		{
			Name:             "artifact.archive",
			Title:            "Archive artifact",
			Description:      "Move a generated artifact and its metadata sidecar into the artifact archive folder.",
			Surface:          "Artifact Studio",
			Risk:             "medium",
			RequiresApproval: true,
			Inputs:           []string{"relPath"},
		},
		{
			Name:             "operations.inspect",
			Title:            "Inspect operations files",
			Description:      "Read Dockerfile, Compose, environment, and service configuration without mutating Docker state.",
			Surface:          "Operations Studio",
			Risk:             "low",
			RequiresApproval: false,
			Inputs:           []string{"relPath"},
		},
	}
}
