package tools

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"

	"nexusdesk/internal/services/agent"
	artifactsSvc "nexusdesk/internal/services/artifacts"
	documentsSvc "nexusdesk/internal/services/documents"
	operationsSvc "nexusdesk/internal/services/operations"
	workspaceSvc "nexusdesk/internal/services/workspace"
)

func (h defaultHandlers) regenerateArtifact(ctx context.Context, call agent.ToolCall, request agent.Request) (agent.ToolResult, error) {
	root, err := workspaceRoot(request)
	if err != nil {
		return toolError(call, "high", err), err
	}
	relPath := firstArg(call, "relPath", "path", "artifact")
	if relPath == "" {
		err := errors.New("relPath is required")
		return toolError(call, "high", err), err
	}
	store, err := artifactsSvc.NewStore(root)
	if err != nil {
		return toolError(call, "high", err), err
	}
	original, err := artifactByExactPath(store, relPath)
	if err != nil {
		return toolError(call, "high", err), err
	}
	if original.Archived {
		err := errors.New("archived artifacts cannot be regenerated")
		return toolError(call, "high", err), err
	}
	rebuilt, err := h.rebuildArtifact(ctx, root, store, original)
	if err != nil {
		return toolError(call, "high", err), err
	}
	return agent.ToolResult{
		Name:    call.Name,
		Args:    call.Args,
		Risk:    "high",
		Mutated: true,
		Observation: fmt.Sprintf(
			"Regenerated %s artifact.\nOriginal: %s\nCreated: %s\nSources: %s",
			rebuilt.Kind,
			original.RelPath,
			rebuilt.RelPath,
			strings.Join(rebuilt.SourcePaths, ", "),
		),
	}, nil
}

func (h defaultHandlers) rebuildArtifact(ctx context.Context, root string, store *artifactsSvc.Store, original artifactsSvc.Artifact) (artifactsSvc.Artifact, error) {
	if err := ctx.Err(); err != nil {
		return artifactsSvc.Artifact{}, err
	}
	switch strings.TrimSpace(original.Kind) {
	case "scan-report":
		report, err := h.deps.Workspace.ScanReport(ctx, root, workspaceSvc.ScanReportOptions{
			MaxDepth:   12,
			MaxEntries: 5000,
			MaxSamples: 12,
		})
		if err != nil {
			return artifactsSvc.Artifact{}, err
		}
		return store.WriteWorkspaceScanReport(workspaceScanArtifactInput(report))
	case "document-report":
		roots, ok := artifactRegenerationSources(original)
		if !ok {
			return artifactsSvc.Artifact{}, fmt.Errorf("document report artifact %s has no source path metadata", original.RelPath)
		}
		pack, err := h.deps.Workspace.BuildContextPack(root, roots, workspaceSvc.ContextPackOptions{
			ContextCollectOptions: workspaceSvc.ContextCollectOptions{
				MaxFiles:   24,
				MaxEntries: 1200,
				MaxDepth:   8,
			},
			MaxBytes: 128 * 1024,
		})
		if err != nil {
			return artifactsSvc.Artifact{}, err
		}
		if err := ctx.Err(); err != nil {
			return artifactsSvc.Artifact{}, err
		}
		return store.WriteDocumentSetReport(artifactsSvc.DocumentSetReport{
			Title:       documentSetArtifactTitleForRoots(roots),
			Roots:       append([]string{}, roots...),
			SourcePaths: pack.SourcePaths,
			Content:     pack.Content,
			Truncated:   pack.Truncated,
			GeneratedBy: "Nexus native agent artifact tool",
		})
	case "document-extract":
		source, ok := artifactRegenerationSource(original)
		if !ok {
			return artifactsSvc.Artifact{}, fmt.Errorf("document extraction artifact %s has no source path metadata", original.RelPath)
		}
		document, err := documentsSvc.New(h.deps.Workspace).Extract(root, source)
		if err != nil {
			return artifactsSvc.Artifact{}, err
		}
		if err := ctx.Err(); err != nil {
			return artifactsSvc.Artifact{}, err
		}
		return store.WriteDocumentExtractionReport(documentExtractionArtifactInput(document))
	case "operations-runbook":
		source, ok := artifactRegenerationSource(original)
		if !ok {
			return artifactsSvc.Artifact{}, fmt.Errorf("operations runbook artifact %s has no source path metadata", original.RelPath)
		}
		inspection, err := operationsSvc.New().InspectContext(ctx, root, source)
		if err != nil {
			return artifactsSvc.Artifact{}, err
		}
		if err := ctx.Err(); err != nil {
			return artifactsSvc.Artifact{}, err
		}
		return store.WriteOperationsRunbook(operationsRunbookArtifactInput(inspection))
	case "artifact-comparison":
		left, right, ok := artifactRegenerationPair(original)
		if !ok {
			return artifactsSvc.Artifact{}, fmt.Errorf("comparison artifact %s has no compared artifact path metadata", original.RelPath)
		}
		comparison, err := store.CompareArtifacts(left, right)
		if err != nil {
			return artifactsSvc.Artifact{}, err
		}
		if err := ctx.Err(); err != nil {
			return artifactsSvc.Artifact{}, err
		}
		return store.WriteArtifactComparisonReport(comparison)
	default:
		return artifactsSvc.Artifact{}, fmt.Errorf("artifact kind %q cannot be regenerated by the agent tool", original.Kind)
	}
}

func artifactByExactPath(store *artifactsSvc.Store, relPath string) (artifactsSvc.Artifact, error) {
	relPath = filepath.ToSlash(strings.TrimSpace(relPath))
	artifacts, err := store.ListArtifacts(artifactsSvc.ListOptions{IncludeArchived: true})
	if err != nil {
		return artifactsSvc.Artifact{}, err
	}
	for _, artifact := range artifacts {
		if artifact.RelPath == relPath {
			return artifact, nil
		}
	}
	return artifactsSvc.Artifact{}, fmt.Errorf("artifact %s was not found", relPath)
}

func artifactRegenerationSource(artifact artifactsSvc.Artifact) (string, bool) {
	sources := normalizeArtifactRegenerationSources(append(append([]string{}, artifact.SourcePaths...), artifact.Source), false)
	if len(sources) == 0 {
		return "", false
	}
	return sources[0], true
}

func artifactRegenerationSources(artifact artifactsSvc.Artifact) ([]string, bool) {
	var candidates []string
	if strings.TrimSpace(artifact.Source) != "" {
		if strings.Contains(artifact.Source, ",") {
			candidates = strings.Split(artifact.Source, ",")
		} else {
			candidates = append(candidates, artifact.Source)
		}
	}
	sources := normalizeArtifactRegenerationSources(candidates, true)
	if len(sources) == 0 {
		sources = normalizeArtifactRegenerationSources(artifact.SourcePaths, true)
	}
	return sources, len(sources) > 0
}

func normalizeArtifactRegenerationSources(candidates []string, allowProjectRoot bool) []string {
	seen := make(map[string]struct{}, len(candidates))
	sources := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		candidate = filepath.ToSlash(strings.TrimSpace(candidate))
		if candidate == "" || strings.Contains(candidate, ",") {
			continue
		}
		if candidate == "." && !allowProjectRoot {
			continue
		}
		if _, ok := seen[candidate]; ok {
			continue
		}
		seen[candidate] = struct{}{}
		sources = append(sources, candidate)
	}
	return sources
}

func artifactRegenerationPair(artifact artifactsSvc.Artifact) (string, string, bool) {
	candidates := append([]string{}, artifact.SourcePaths...)
	if len(candidates) < 2 {
		candidates = nil
		if strings.Contains(artifact.Source, ",") {
			candidates = strings.Split(artifact.Source, ",")
		}
	}
	paths := make([]string, 0, 2)
	for _, candidate := range candidates {
		candidate = filepath.ToSlash(strings.TrimSpace(candidate))
		if candidate == "" || candidate == "." || strings.Contains(candidate, ",") {
			continue
		}
		paths = append(paths, candidate)
		if len(paths) == 2 {
			break
		}
	}
	if len(paths) != 2 || paths[0] == paths[1] {
		return "", "", false
	}
	return paths[0], paths[1], true
}

func workspaceScanArtifactInput(report workspaceSvc.ScanReport) artifactsSvc.WorkspaceScanReport {
	return artifactsSvc.WorkspaceScanReport{
		WorkspaceName:  report.Name,
		Included:       report.Included,
		Ignored:        report.Ignored,
		DepthSkipped:   report.DepthSkipped,
		EntrySkipped:   report.EntrySkipped,
		Unreadable:     report.Unreadable,
		MaxDepth:       report.MaxDepth,
		MaxEntries:     report.MaxEntries,
		Truncated:      report.Truncated,
		IgnoredSamples: append([]string{}, report.IgnoredSamples...),
		SkippedSamples: append([]string{}, report.SkippedSamples...),
		Message:        report.Message(),
	}
}

func documentExtractionArtifactInput(document documentsSvc.ExtractedDocument) artifactsSvc.DocumentExtractionReport {
	return artifactsSvc.DocumentExtractionReport{
		Title:     document.Title,
		RelPath:   document.RelPath,
		Format:    document.Format,
		MediaType: document.MediaType,
		Encoding:  document.Encoding,
		Content:   document.Text,
		Size:      document.Size,
		Lines:     document.Lines,
		Words:     document.Words,
		Pages:     document.Pages,
		Truncated: document.Truncated,
	}
}

func documentSetArtifactTitleForRoots(roots []string) string {
	roots = normalizeArtifactRegenerationSources(roots, true)
	if len(roots) == 0 || (len(roots) == 1 && roots[0] == ".") {
		return "Project Document Set Report"
	}
	if len(roots) == 1 {
		return "Document Set Report - " + roots[0]
	}
	return fmt.Sprintf("Document Set Report - %d sources", len(roots))
}

func operationsRunbookArtifactInput(inspection operationsSvc.Inspection) artifactsSvc.OperationsRunbookReport {
	services := make([]artifactsSvc.OperationsServiceSummary, 0, len(inspection.Services))
	for _, service := range inspection.Services {
		services = append(services, artifactsSvc.OperationsServiceSummary{
			Name:      service.Name,
			Image:     service.Image,
			Ports:     append([]string{}, service.Ports...),
			Volumes:   append([]string{}, service.Volumes...),
			DependsOn: append([]string{}, service.DependsOn...),
		})
	}
	topologyEdges := make([]artifactsSvc.OperationsTopologyEdge, 0, len(inspection.Topology.Edges))
	for _, edge := range inspection.Topology.Edges {
		topologyEdges = append(topologyEdges, artifactsSvc.OperationsTopologyEdge{
			From:     edge.From,
			To:       edge.To,
			Relation: edge.Relation,
			Missing:  edge.Missing,
		})
	}
	exposedPorts := make([]artifactsSvc.OperationsPortExposure, 0, len(inspection.Topology.ExposedPorts))
	for _, exposure := range inspection.Topology.ExposedPorts {
		exposedPorts = append(exposedPorts, artifactsSvc.OperationsPortExposure{
			Service: exposure.Service,
			Port:    exposure.Port,
		})
	}
	warnings := append([]string{}, inspection.Warnings...)
	warnings = append(warnings, inspection.Topology.Warnings...)
	return artifactsSvc.OperationsRunbookReport{
		Title:           "Operations Runbook - " + inspection.File.Name,
		SourcePath:      inspection.File.RelPath,
		Kind:            string(inspection.File.Kind),
		Size:            inspection.File.Size,
		Content:         formatOperationsInspection(inspection),
		Services:        services,
		TopologySummary: inspection.Topology.Summary,
		TopologyEdges:   topologyEdges,
		ExposedPorts:    exposedPorts,
		NamedVolumes:    append([]string{}, inspection.Topology.NamedVolumes...),
		Warnings:        warnings,
		Truncated:       inspection.Truncated,
		GeneratedBy:     "Nexus native operations inspector",
	}
}

func formatOperationsInspection(inspection operationsSvc.Inspection) string {
	var builder strings.Builder
	builder.WriteString("# Operations Inspection\n\n")
	builder.WriteString("Path: ")
	builder.WriteString(inspection.File.RelPath)
	builder.WriteString("\nKind: ")
	builder.WriteString(string(inspection.File.Kind))
	builder.WriteString(fmt.Sprintf("\nSize: %d bytes\n", inspection.File.Size))
	for _, warning := range inspection.Warnings {
		builder.WriteString("Warning: ")
		builder.WriteString(warning)
		builder.WriteString("\n")
	}
	if len(inspection.Services) > 0 {
		builder.WriteString("\nCompose Services\n")
		for _, service := range inspection.Services {
			builder.WriteString("- ")
			builder.WriteString(service.Name)
			if service.Image != "" {
				builder.WriteString(" | image: ")
				builder.WriteString(service.Image)
			}
			if len(service.Ports) > 0 {
				builder.WriteString(" | ports: ")
				builder.WriteString(strings.Join(service.Ports, ", "))
			}
			if len(service.DependsOn) > 0 {
				builder.WriteString(" | depends on: ")
				builder.WriteString(strings.Join(service.DependsOn, ", "))
			}
			builder.WriteString("\n")
		}
	}
	if inspection.Topology.Summary != "" {
		builder.WriteString("\nCompose Topology\n")
		builder.WriteString(inspection.Topology.Summary)
		builder.WriteString("\n")
	}
	builder.WriteString("\nContent\n\n")
	builder.WriteString(inspection.Text)
	return builder.String()
}
