package artifacts

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"
)

const (
	documentBriefSummaryLimit  = 4
	documentBriefKeyPointLimit = 8
	documentBriefRiskLimit     = 6
	documentBriefNextStepLimit = 6
	documentBriefLineMaxRunes  = 180
)

func BuildDocumentBriefReport(title string, sourcePath string, sourceTitle string, sourceKind string, sourceText string, sourcePaths []string) DocumentBriefReport {
	sourceTitle = strings.TrimSpace(sourceTitle)
	title = strings.TrimSpace(title)
	if title == "" {
		title = documentBriefTitle(sourceTitle, sourcePath)
	}
	content, sectionCount := documentBriefContent(sourceText)
	return DocumentBriefReport{
		Title:        title,
		SourcePath:   filepath.ToSlash(strings.TrimSpace(sourcePath)),
		SourceTitle:  sourceTitle,
		SourceKind:   strings.TrimSpace(sourceKind),
		SourcePaths:  append([]string{}, sourcePaths...),
		Content:      content,
		SectionCount: sectionCount,
		GeneratedBy:  "Nexus native document brief writer",
	}
}

func (s *Store) WriteDocumentBriefReport(report DocumentBriefReport) (Artifact, error) {
	content := strings.TrimSpace(report.Content)
	if content == "" {
		return Artifact{}, errors.New("document brief content is required")
	}
	createdAt := time.Now().UTC()
	title := strings.TrimSpace(report.Title)
	if title == "" {
		title = documentBriefTitle(report.SourceTitle, report.SourcePath)
	}
	sourcePaths := documentBriefSourcePaths(report.SourcePath, report.SourcePaths)
	markdown := documentBriefMarkdown(report, title, sourcePaths, createdAt)
	relPath, absPath, file, err := s.createUniqueArtifactFile("document-briefs", title, ".md", createdAt)
	if err != nil {
		return Artifact{}, err
	}
	defer file.Close()
	if _, err := file.WriteString(markdown); err != nil {
		return Artifact{}, err
	}
	metadata := Metadata{
		Kind:        "document-brief",
		Title:       title,
		RelPath:     relPath,
		Source:      filepath.ToSlash(strings.TrimSpace(report.SourcePath)),
		SourcePaths: sourcePaths,
		GeneratedAt: createdAt,
	}
	if err := s.writeMetadata(metadata); err != nil {
		return Artifact{}, err
	}
	return Artifact{
		Kind:         "document-brief",
		Title:        title,
		RelPath:      relPath,
		AbsPath:      absPath,
		MetadataPath: relPath + ".json",
		Message:      "Document brief artifact created at " + relPath + ".",
		Size:         int64(len(markdown)),
		CreatedAt:    createdAt,
		GeneratedAt:  createdAt,
		Source:       metadata.Source,
		SourcePaths:  append([]string{}, sourcePaths...),
	}, nil
}

func documentBriefMarkdown(report DocumentBriefReport, title string, sourcePaths []string, createdAt time.Time) string {
	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	writeKV(&builder, "Generated", formatArtifactTime(createdAt))
	writeKV(&builder, "Generated by", firstNonEmptyArtifact(report.GeneratedBy, "Nexus native document brief writer"))
	writeKV(&builder, "Source artifact", report.SourcePath)
	writeKV(&builder, "Source title", report.SourceTitle)
	writeKV(&builder, "Source kind", report.SourceKind)
	writeKV(&builder, "Sections", fmt.Sprintf("%d", firstNonZeroInt(report.SectionCount, countDocumentBriefSections(report.Content))))
	if len(sourcePaths) > 0 {
		builder.WriteString("\n## Sources\n\n")
		for _, source := range sourcePaths {
			builder.WriteString("- ")
			builder.WriteString(source)
			builder.WriteString("\n")
		}
	}
	builder.WriteString("\n## Brief\n\n")
	builder.WriteString(strings.TrimSpace(report.Content))
	builder.WriteString("\n")
	return builder.String()
}

func documentBriefContent(markdown string) (string, int) {
	lines := strings.Split(strings.ReplaceAll(markdown, "\r\n", "\n"), "\n")
	summary := []string{}
	keyPoints := []string{}
	risks := []string{}
	nextSteps := []string{}
	for _, rawLine := range lines {
		line := documentBriefCleanLine(rawLine)
		if line == "" {
			continue
		}
		lower := strings.ToLower(line)
		if len(summary) < documentBriefSummaryLimit && documentBriefSummaryCandidate(line) {
			summary = append(summary, line)
		}
		if len(keyPoints) < documentBriefKeyPointLimit && documentBriefKeyPointCandidate(line) {
			keyPoints = append(keyPoints, line)
		}
		if len(risks) < documentBriefRiskLimit && documentBriefContainsAny(lower, []string{"risk", "warning", "blocker", "missing", "error", "failed", "failure", "todo"}) {
			risks = append(risks, line)
		}
		if len(nextSteps) < documentBriefNextStepLimit && documentBriefContainsAny(lower, []string{"next", "follow", "should", "todo", "action", "implement", "review"}) {
			nextSteps = append(nextSteps, line)
		}
	}
	if len(summary) == 0 {
		summary = []string{"Review the source artifact for context, findings, and follow-up work."}
	}
	if len(keyPoints) == 0 {
		keyPoints = append([]string{}, summary...)
	}
	if len(risks) == 0 {
		risks = []string{"No explicit risks or blockers were detected in the source artifact."}
	}
	if len(nextSteps) == 0 {
		nextSteps = []string{"Review the cited sources and decide whether this brief should become a formal report or deck."}
	}
	var builder strings.Builder
	writeDocumentBriefSection(&builder, "Executive Summary", summary)
	writeDocumentBriefSection(&builder, "Key Points", keyPoints)
	writeDocumentBriefSection(&builder, "Risks And Gaps", risks)
	writeDocumentBriefSection(&builder, "Suggested Next Steps", nextSteps)
	return strings.TrimSpace(builder.String()), 4
}

func writeDocumentBriefSection(builder *strings.Builder, title string, values []string) {
	if builder.Len() > 0 {
		builder.WriteString("\n\n")
	}
	builder.WriteString("### ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	for _, value := range values {
		builder.WriteString("- ")
		builder.WriteString(value)
		builder.WriteString("\n")
	}
}

func documentBriefCleanLine(line string) string {
	line = strings.TrimSpace(line)
	if line == "" || line == "---" || strings.HasPrefix(line, "```") || strings.HasPrefix(line, "|") {
		return ""
	}
	if strings.HasPrefix(line, "- **") && strings.Contains(line, ":**") {
		return ""
	}
	if strings.HasPrefix(strings.ToLower(line), "workspace context:") {
		return ""
	}
	if title, ok := markdownHeadingTitle(line); ok {
		return documentBriefTrimLine(title)
	}
	line = presentationBulletText(line)
	return documentBriefTrimLine(line)
}

func documentBriefSummaryCandidate(line string) bool {
	if strings.TrimSpace(line) == "" {
		return false
	}
	return len([]rune(line)) >= 12
}

func documentBriefKeyPointCandidate(line string) bool {
	return strings.TrimSpace(line) != ""
}

func documentBriefContainsAny(value string, needles []string) bool {
	for _, needle := range needles {
		if strings.Contains(value, needle) {
			return true
		}
	}
	return false
}

func documentBriefTrimLine(value string) string {
	value = strings.Join(strings.Fields(strings.TrimSpace(value)), " ")
	runes := []rune(value)
	if len(runes) <= documentBriefLineMaxRunes {
		return value
	}
	return strings.TrimSpace(string(runes[:documentBriefLineMaxRunes-3])) + "..."
}

func documentBriefTitle(sourceTitle string, sourcePath string) string {
	sourceTitle = strings.TrimSpace(sourceTitle)
	for _, prefix := range []string{"Document Brief - ", "Document Set Report - ", "Assistant Answer - ", "Presentation Outline - "} {
		sourceTitle = strings.TrimPrefix(sourceTitle, prefix)
	}
	if sourceTitle != "" {
		return "Document Brief - " + sourceTitle
	}
	sourcePath = filepath.ToSlash(strings.TrimSpace(sourcePath))
	if sourcePath != "" {
		name := strings.TrimSuffix(filepath.Base(sourcePath), filepath.Ext(sourcePath))
		if strings.TrimSpace(name) != "" {
			return "Document Brief - " + name
		}
	}
	return "Document Brief"
}

func documentBriefSourcePaths(sourcePath string, sourcePaths []string) []string {
	candidates := append([]string{sourcePath}, sourcePaths...)
	seen := map[string]bool{}
	out := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		candidate = filepath.ToSlash(strings.TrimSpace(candidate))
		if candidate == "" || seen[candidate] {
			continue
		}
		seen[candidate] = true
		out = append(out, candidate)
	}
	return out
}

func countDocumentBriefSections(content string) int {
	count := 0
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "### ") {
			count++
		}
	}
	return count
}
