package artifacts

import (
	"os"
	"strings"
	"testing"
)

func TestWriteDocumentSetReportCreatesMarkdownArtifact(t *testing.T) {
	store, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	artifact, err := store.WriteDocumentSetReport(DocumentSetReport{
		Title:       "Architecture Notes",
		Roots:       []string{"docs"},
		SourcePaths: []string{"docs/01.md", "docs/02.md"},
		Content:     "Workspace context pack\n\n---\nWorkspace context: docs/01.md\n\nhello",
		Truncated:   true,
		GeneratedBy: "test",
	})
	if err != nil {
		t.Fatalf("WriteDocumentSetReport returned error: %v", err)
	}
	if artifact.Kind != "document-report" || artifact.MetadataPath == "" || len(artifact.SourcePaths) != 2 {
		t.Fatalf("expected metadata-backed document artifact, got %#v", artifact)
	}
	if !strings.HasPrefix(artifact.RelPath, ".nexusdesk/artifacts/document-sets/") {
		t.Fatalf("unexpected artifact path: %q", artifact.RelPath)
	}
	data, err := os.ReadFile(artifact.AbsPath)
	if err != nil {
		t.Fatalf("expected report file: %v", err)
	}
	text := string(data)
	for _, expected := range []string{"# Architecture Notes", "Generated by:** test", "Source files:** 2", "Truncated:** true", "docs/01.md", "hello"} {
		if !strings.Contains(text, expected) {
			t.Fatalf("expected document report to contain %q, got:\n%s", expected, text)
		}
	}

	artifacts, err := store.ListArtifacts(ListOptions{Query: "kind:document-report"})
	if err != nil {
		t.Fatalf("ListArtifacts returned error: %v", err)
	}
	if len(artifacts) != 1 || artifacts[0].RelPath != artifact.RelPath {
		t.Fatalf("expected document report in artifact list, got %#v", artifacts)
	}
	lineage, err := store.Lineage(artifact.RelPath)
	if err != nil {
		t.Fatalf("Lineage returned error: %v", err)
	}
	if len(lineage.Nodes) < 3 || len(lineage.Edges) < 2 {
		t.Fatalf("expected source lineage, got %#v", lineage)
	}
}

func TestWriteDocumentSetReportRequiresContent(t *testing.T) {
	store, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if _, err := store.WriteDocumentSetReport(DocumentSetReport{Title: "Empty"}); err == nil {
		t.Fatal("expected empty document report to be rejected")
	}
}
