package artifacts

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func (s *Store) WriteDocumentSetReport(report DocumentSetReport) (Artifact, error) {
	content := strings.TrimSpace(report.Content)
	if content == "" {
		return Artifact{}, errors.New("document report content is required")
	}
	createdAt := time.Now().UTC()
	title := strings.TrimSpace(report.Title)
	if title == "" {
		title = documentSetTitle(report.Roots)
	}
	relPath := s.relPath("document-sets", fmt.Sprintf("%s-%s.md", artifactTimestamp(createdAt), safeName(title)))
	absPath := s.absPath(relPath)
	if err := os.MkdirAll(filepath.Dir(absPath), 0o755); err != nil {
		return Artifact{}, err
	}
	markdown := documentSetMarkdown(report, title, createdAt)
	file, err := os.OpenFile(absPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return Artifact{}, err
	}
	defer file.Close()
	if _, err := file.WriteString(markdown); err != nil {
		return Artifact{}, err
	}
	metadata := Metadata{
		Kind:        "document-report",
		Title:       title,
		RelPath:     relPath,
		Source:      strings.Join(report.Roots, ", "),
		SourcePaths: append([]string{}, report.SourcePaths...),
		GeneratedAt: createdAt,
	}
	if err := s.writeMetadata(metadata); err != nil {
		return Artifact{}, err
	}
	return Artifact{
		Kind:         "document-report",
		Title:        title,
		RelPath:      relPath,
		AbsPath:      absPath,
		MetadataPath: relPath + ".json",
		Message:      "Document-set report artifact created at " + relPath + ".",
		Size:         int64(len(markdown)),
		CreatedAt:    createdAt,
		GeneratedAt:  createdAt,
		Source:       metadata.Source,
		SourcePaths:  append([]string{}, report.SourcePaths...),
	}, nil
}

func documentSetMarkdown(report DocumentSetReport, title string, createdAt time.Time) string {
	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	writeKV(&builder, "Generated", formatArtifactTime(createdAt))
	writeKV(&builder, "Generated by", firstNonEmptyArtifact(report.GeneratedBy, "Nexus native document-set writer"))
	writeKV(&builder, "Roots", strings.Join(report.Roots, ", "))
	writeKV(&builder, "Source files", fmt.Sprintf("%d", len(report.SourcePaths)))
	writeKV(&builder, "Truncated", fmt.Sprintf("%t", report.Truncated))
	if len(report.SourcePaths) > 0 {
		builder.WriteString("\n## Sources\n\n")
		for _, source := range report.SourcePaths {
			builder.WriteString("- ")
			builder.WriteString(source)
			builder.WriteString("\n")
		}
	}
	builder.WriteString("\n## Extracted Document Context\n\n")
	builder.WriteString(strings.TrimSpace(report.Content))
	builder.WriteString("\n")
	return builder.String()
}

func documentSetTitle(roots []string) string {
	if len(roots) == 0 {
		return "Document Set Report"
	}
	if len(roots) == 1 {
		root := strings.TrimSpace(roots[0])
		if root == "" || root == "." {
			return "Project Document Set Report"
		}
		return "Document Set Report - " + root
	}
	return fmt.Sprintf("Document Set Report - %d roots", len(roots))
}

func firstNonEmptyArtifact(values ...string) string {
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			return value
		}
	}
	return ""
}
