package artifacts

import (
	"os"
	"strings"
	"testing"
)

func TestBuildDocumentBriefReportExtractsSections(t *testing.T) {
	report := BuildDocumentBriefReport(
		"",
		".nexusdesk/artifacts/document-sets/report.md",
		"Document Set Report - Architecture Notes",
		"document-report",
		"# Architecture Notes\n\nThe native shell keeps useful Wails features while removing webview runtime risk.\n\n## Gaps\n\n- Missing durable routing for slow jobs remains a production blocker.\n- Teams should review packaging smoke tests before release.\n- Next action: verify source citations and regenerate the deck.\n",
		[]string{"docs/a.md"},
	)
	if report.Title != "Document Brief - Architecture Notes" || report.SourcePath == "" || report.SectionCount != 4 {
		t.Fatalf("unexpected document brief report metadata: %#v", report)
	}
	for _, expected := range []string{"### Executive Summary", "native shell keeps useful Wails features", "### Key Points", "Architecture Notes", "### Risks And Gaps", "production blocker", "### Suggested Next Steps", "Next action"} {
		if !strings.Contains(report.Content, expected) {
			t.Fatalf("document brief missing %q:\n%s", expected, report.Content)
		}
	}
}

func TestWriteDocumentBriefReportCreatesMarkdownArtifact(t *testing.T) {
	store, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	artifact, err := store.WriteDocumentBriefReport(DocumentBriefReport{
		Title:        "Document Brief - Architecture Notes",
		SourcePath:   ".nexusdesk/artifacts/document-sets/report.md",
		SourceTitle:  "Architecture Notes",
		SourceKind:   "document-report",
		SourcePaths:  []string{"docs/a.md", "docs/b.md"},
		Content:      "### Executive Summary\n\n- Native parity is close.\n",
		SectionCount: 1,
		GeneratedBy:  "test",
	})
	if err != nil {
		t.Fatalf("WriteDocumentBriefReport returned error: %v", err)
	}
	if artifact.Kind != "document-brief" || artifact.MetadataPath == "" || len(artifact.SourcePaths) != 3 {
		t.Fatalf("expected metadata-backed document brief artifact, got %#v", artifact)
	}
	if artifact.SourcePaths[0] != ".nexusdesk/artifacts/document-sets/report.md" {
		t.Fatalf("expected source artifact first in source paths, got %#v", artifact.SourcePaths)
	}
	if !strings.HasPrefix(artifact.RelPath, ".nexusdesk/artifacts/document-briefs/") {
		t.Fatalf("unexpected artifact path: %q", artifact.RelPath)
	}
	data, err := os.ReadFile(artifact.AbsPath)
	if err != nil {
		t.Fatalf("expected brief file: %v", err)
	}
	text := string(data)
	for _, expected := range []string{"# Document Brief - Architecture Notes", "Generated by:** test", "Source artifact:** .nexusdesk/artifacts/document-sets/report.md", "Source kind:** document-report", "docs/a.md", "Native parity is close."} {
		if !strings.Contains(text, expected) {
			t.Fatalf("expected document brief to contain %q, got:\n%s", expected, text)
		}
	}

	artifacts, err := store.ListArtifacts(ListOptions{Query: "kind:document-brief"})
	if err != nil {
		t.Fatalf("ListArtifacts returned error: %v", err)
	}
	if len(artifacts) != 1 || artifacts[0].RelPath != artifact.RelPath {
		t.Fatalf("expected document brief in artifact list, got %#v", artifacts)
	}
	lineage, err := store.Lineage(artifact.RelPath)
	if err != nil {
		t.Fatalf("Lineage returned error: %v", err)
	}
	if len(lineage.Nodes) < 4 || len(lineage.Edges) < 3 {
		t.Fatalf("expected source lineage, got %#v", lineage)
	}
}

func TestWriteDocumentBriefReportRequiresContent(t *testing.T) {
	store, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if _, err := store.WriteDocumentBriefReport(DocumentBriefReport{Title: "Empty"}); err == nil {
		t.Fatal("expected empty document brief to be rejected")
	}
}

func TestInferKindDetectsDocumentBriefs(t *testing.T) {
	if got := inferKind(".nexusdesk/artifacts/document-briefs/brief.md"); got != "document-brief" {
		t.Fatalf("unexpected document brief kind: %q", got)
	}
}
