package artifacts

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func (s *Store) WriteOperationsRunbook(report OperationsRunbookReport) (Artifact, error) {
	source := strings.TrimSpace(report.SourcePath)
	if source == "" {
		return Artifact{}, errors.New("operations runbook source path is required")
	}
	content := strings.TrimSpace(report.Content)
	if content == "" && len(report.Services) == 0 && len(report.Warnings) == 0 {
		return Artifact{}, errors.New("operations runbook evidence is required")
	}
	createdAt := time.Now().UTC()
	title := strings.TrimSpace(report.Title)
	if title == "" {
		title = "Operations Runbook - " + filepath.Base(source)
	}
	relPath := s.relPath("operations-runbooks", fmt.Sprintf("%s-%s.md", createdAt.Format("20060102-150405-000000000"), safeName(title)))
	absPath := s.absPath(relPath)
	if err := os.MkdirAll(filepath.Dir(absPath), 0o755); err != nil {
		return Artifact{}, err
	}
	markdown := operationsRunbookMarkdown(report, title, createdAt)
	file, err := os.OpenFile(absPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return Artifact{}, err
	}
	defer file.Close()
	if _, err := file.WriteString(markdown); err != nil {
		return Artifact{}, err
	}
	metadata := Metadata{
		Kind:        "operations-runbook",
		Title:       title,
		RelPath:     relPath,
		Source:      operationsRunbookSourceSummary(report),
		SourcePaths: []string{source},
		GeneratedAt: createdAt,
	}
	if err := s.writeMetadata(metadata); err != nil {
		return Artifact{}, err
	}
	return Artifact{
		Kind:         "operations-runbook",
		Title:        title,
		RelPath:      relPath,
		AbsPath:      absPath,
		MetadataPath: relPath + ".json",
		Message:      "Operations runbook artifact created at " + relPath + ".",
		Size:         int64(len(markdown)),
		CreatedAt:    createdAt,
		GeneratedAt:  createdAt,
		Source:       metadata.Source,
		SourcePaths:  []string{source},
	}, nil
}

func operationsRunbookMarkdown(report OperationsRunbookReport, title string, createdAt time.Time) string {
	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	writeKV(&builder, "Generated", formatArtifactTime(createdAt))
	writeKV(&builder, "Generated by", firstNonEmptyArtifact(report.GeneratedBy, "Nexus native operations inspector"))
	writeKV(&builder, "Source", report.SourcePath)
	writeKV(&builder, "Kind", report.Kind)
	writeKV(&builder, "Size", fmt.Sprintf("%d bytes", report.Size))
	writeKV(&builder, "Truncated", fmt.Sprintf("%t", report.Truncated))

	if len(report.Warnings) > 0 {
		builder.WriteString("\n## Safety Notes\n\n")
		for _, warning := range report.Warnings {
			warning = strings.TrimSpace(warning)
			if warning == "" {
				continue
			}
			builder.WriteString("- ")
			builder.WriteString(warning)
			builder.WriteString("\n")
		}
	}

	if len(report.Services) > 0 {
		builder.WriteString("\n## Compose Services\n\n")
		for _, service := range report.Services {
			builder.WriteString("- **")
			builder.WriteString(firstNonEmptyArtifact(service.Name, "unnamed"))
			builder.WriteString("**")
			details := operationsServiceDetails(service)
			if details != "" {
				builder.WriteString(" - ")
				builder.WriteString(details)
			}
			builder.WriteString("\n")
		}
	}

	if strings.TrimSpace(report.TopologySummary) != "" || len(report.TopologyEdges) > 0 || len(report.ExposedPorts) > 0 || len(report.NamedVolumes) > 0 {
		builder.WriteString("\n## Compose Topology\n\n")
		if strings.TrimSpace(report.TopologySummary) != "" {
			builder.WriteString(report.TopologySummary)
			builder.WriteString("\n")
		}
		if len(report.TopologyEdges) > 0 {
			builder.WriteString("\nDependencies:\n")
			for _, edge := range report.TopologyEdges {
				builder.WriteString("- ")
				builder.WriteString(edge.From)
				builder.WriteString(" -> ")
				builder.WriteString(edge.To)
				if edge.Relation != "" {
					builder.WriteString(" (")
					builder.WriteString(edge.Relation)
					builder.WriteString(")")
				}
				if edge.Missing {
					builder.WriteString(" [missing target]")
				}
				builder.WriteString("\n")
			}
		}
		if len(report.ExposedPorts) > 0 {
			builder.WriteString("\nExposed ports:\n")
			for _, exposure := range report.ExposedPorts {
				builder.WriteString("- ")
				builder.WriteString(exposure.Service)
				builder.WriteString(" exposes ")
				builder.WriteString(exposure.Port)
				builder.WriteString("\n")
			}
		}
		if len(report.NamedVolumes) > 0 {
			builder.WriteString("\nNamed volumes: ")
			builder.WriteString(strings.Join(report.NamedVolumes, ", "))
			builder.WriteString("\n")
		}
	}

	builder.WriteString("\n## Operator Checklist\n\n")
	builder.WriteString("- Confirm the source file still matches the generated runbook before use.\n")
	builder.WriteString("- Review environment and secret references; redacted values require local operator knowledge.\n")
	builder.WriteString("- Treat all start, stop, build, pull, exec, and database mutation actions as approval-gated follow-up work.\n")

	if strings.TrimSpace(report.Content) != "" {
		builder.WriteString("\n## Source Evidence\n\n")
		builder.WriteString(strings.TrimSpace(report.Content))
		builder.WriteString("\n")
	}
	return builder.String()
}

func operationsServiceDetails(service OperationsServiceSummary) string {
	parts := []string{}
	if strings.TrimSpace(service.Image) != "" {
		parts = append(parts, "image: "+strings.TrimSpace(service.Image))
	}
	if len(service.Ports) > 0 {
		parts = append(parts, "ports: "+strings.Join(service.Ports, ", "))
	}
	if len(service.Volumes) > 0 {
		parts = append(parts, "volumes: "+strings.Join(service.Volumes, ", "))
	}
	if len(service.DependsOn) > 0 {
		parts = append(parts, "depends on: "+strings.Join(service.DependsOn, ", "))
	}
	return strings.Join(parts, " | ")
}

func operationsRunbookSourceSummary(report OperationsRunbookReport) string {
	parts := []string{report.SourcePath}
	if report.Kind != "" {
		parts = append(parts, "kind: "+report.Kind)
	}
	if len(report.Services) > 0 {
		parts = append(parts, fmt.Sprintf("services: %d", len(report.Services)))
	}
	if report.Truncated {
		parts = append(parts, "bounded sample")
	}
	return strings.Join(parts, " | ")
}
