package artifacts

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	presentationMaxSlides          = 12
	presentationMaxBulletsPerSlide = 6
	presentationMaxBulletLength    = 180
)

type presentationSlide struct {
	Title   string
	Bullets []string
}

func BuildPresentationOutlineReport(title string, sourcePath string, sourceTitle string, sourceKind string, sourceText string, sourcePaths []string) PresentationOutlineReport {
	sourceTitle = strings.TrimSpace(sourceTitle)
	title = strings.TrimSpace(title)
	if title == "" {
		title = presentationOutlineTitle(sourceTitle, sourcePath)
	}
	slides := presentationSlidesFromMarkdown(sourceText)
	content := presentationOutlineContent(slides)
	return PresentationOutlineReport{
		Title:       title,
		SourcePath:  filepath.ToSlash(strings.TrimSpace(sourcePath)),
		SourceTitle: sourceTitle,
		SourceKind:  strings.TrimSpace(sourceKind),
		SourcePaths: append([]string{}, sourcePaths...),
		Content:     content,
		SlideCount:  len(slides),
		GeneratedBy: "Nexus native presentation outline writer",
	}
}

func (s *Store) WritePresentationOutlineReport(report PresentationOutlineReport) (Artifact, error) {
	content := strings.TrimSpace(report.Content)
	if content == "" {
		return Artifact{}, errors.New("presentation outline content is required")
	}
	createdAt := time.Now().UTC()
	title := strings.TrimSpace(report.Title)
	if title == "" {
		title = presentationOutlineTitle(report.SourceTitle, report.SourcePath)
	}
	relPath := s.relPath("presentations", fmt.Sprintf("%s-%s.md", artifactTimestamp(createdAt), safeName(title)))
	absPath := s.absPath(relPath)
	if err := os.MkdirAll(filepath.Dir(absPath), 0o755); err != nil {
		return Artifact{}, err
	}
	sourcePaths := presentationOutlineSourcePaths(report.SourcePath, report.SourcePaths)
	markdown := presentationOutlineMarkdown(report, title, sourcePaths, createdAt)
	file, err := os.OpenFile(absPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return Artifact{}, err
	}
	defer file.Close()
	if _, err := file.WriteString(markdown); err != nil {
		return Artifact{}, err
	}
	metadata := Metadata{
		Kind:        "presentation-outline",
		Title:       title,
		RelPath:     relPath,
		Source:      filepath.ToSlash(strings.TrimSpace(report.SourcePath)),
		SourcePaths: sourcePaths,
		GeneratedAt: createdAt,
	}
	if err := s.writeMetadata(metadata); err != nil {
		return Artifact{}, err
	}
	return Artifact{
		Kind:         "presentation-outline",
		Title:        title,
		RelPath:      relPath,
		AbsPath:      absPath,
		MetadataPath: relPath + ".json",
		Message:      "Presentation outline artifact created at " + relPath + ".",
		Size:         int64(len(markdown)),
		CreatedAt:    createdAt,
		GeneratedAt:  createdAt,
		Source:       metadata.Source,
		SourcePaths:  append([]string{}, sourcePaths...),
	}, nil
}

func presentationOutlineMarkdown(report PresentationOutlineReport, title string, sourcePaths []string, createdAt time.Time) string {
	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	writeKV(&builder, "Generated", formatArtifactTime(createdAt))
	writeKV(&builder, "Generated by", firstNonEmptyArtifact(report.GeneratedBy, "Nexus native presentation outline writer"))
	writeKV(&builder, "Source artifact", report.SourcePath)
	writeKV(&builder, "Source title", report.SourceTitle)
	writeKV(&builder, "Source kind", report.SourceKind)
	writeKV(&builder, "Slides", fmt.Sprintf("%d", firstNonZeroInt(report.SlideCount, countPresentationSlides(report.Content))))
	if len(sourcePaths) > 0 {
		builder.WriteString("\n## Sources\n\n")
		for _, source := range sourcePaths {
			builder.WriteString("- ")
			builder.WriteString(source)
			builder.WriteString("\n")
		}
	}
	builder.WriteString("\n## Slide Outline\n\n")
	builder.WriteString(strings.TrimSpace(report.Content))
	builder.WriteString("\n")
	return builder.String()
}

func presentationSlidesFromMarkdown(markdown string) []presentationSlide {
	lines := strings.Split(strings.ReplaceAll(markdown, "\r\n", "\n"), "\n")
	slides := make([]presentationSlide, 0, presentationMaxSlides)
	var current *presentationSlide
	var fallback []string
	for _, rawLine := range lines {
		line := strings.TrimSpace(rawLine)
		if line == "" || line == "---" {
			continue
		}
		if title, ok := markdownHeadingTitle(line); ok {
			if current != nil && len(slides) < presentationMaxSlides {
				slides = append(slides, *current)
			}
			current = &presentationSlide{Title: title}
			continue
		}
		bullet := presentationBulletText(line)
		if bullet == "" {
			continue
		}
		if current == nil {
			if len(fallback) < presentationMaxBulletsPerSlide {
				fallback = append(fallback, bullet)
			}
			continue
		}
		if len(current.Bullets) < presentationMaxBulletsPerSlide {
			current.Bullets = append(current.Bullets, bullet)
		}
	}
	if current != nil && len(slides) < presentationMaxSlides {
		slides = append(slides, *current)
	}
	if len(slides) == 0 {
		slides = append(slides, presentationSlide{Title: "Summary", Bullets: fallback})
	}
	return compactPresentationSlides(slides)
}

func markdownHeadingTitle(line string) (string, bool) {
	if !strings.HasPrefix(line, "#") {
		return "", false
	}
	level := 0
	for level < len(line) && line[level] == '#' {
		level++
	}
	if level == 0 || level > 3 || level >= len(line) || line[level] != ' ' {
		return "", false
	}
	title := strings.TrimSpace(line[level:])
	if title == "" {
		return "", false
	}
	return presentationTrimBullet(title), true
}

func presentationBulletText(line string) string {
	line = strings.TrimSpace(line)
	if line == "" {
		return ""
	}
	line = strings.TrimPrefix(line, ">")
	line = strings.TrimSpace(line)
	if strings.HasPrefix(line, "- **") && strings.Contains(line, ":**") {
		return ""
	}
	if strings.HasPrefix(strings.ToLower(line), "workspace context:") {
		return ""
	}
	for _, prefix := range []string{"- ", "* ", "+ "} {
		if strings.HasPrefix(line, prefix) {
			return presentationTrimBullet(strings.TrimSpace(strings.TrimPrefix(line, prefix)))
		}
	}
	if numberedListIndex(line) > 0 {
		return presentationTrimBullet(strings.TrimSpace(line[numberedListIndex(line):]))
	}
	if strings.HasPrefix(line, "```") || strings.HasPrefix(line, "|") {
		return ""
	}
	return presentationTrimBullet(line)
}

func numberedListIndex(line string) int {
	index := 0
	for index < len(line) && line[index] >= '0' && line[index] <= '9' {
		index++
	}
	if index == 0 || index+1 >= len(line) || line[index] != '.' || line[index+1] != ' ' {
		return 0
	}
	return index + 2
}

func compactPresentationSlides(slides []presentationSlide) []presentationSlide {
	out := make([]presentationSlide, 0, len(slides))
	for _, slide := range slides {
		slide.Title = presentationTrimBullet(slide.Title)
		if slide.Title == "" {
			slide.Title = "Slide"
		}
		if len(slide.Bullets) == 0 {
			slide.Bullets = []string{"Use this slide to introduce " + strings.ToLower(slide.Title) + "."}
		}
		out = append(out, slide)
		if len(out) == presentationMaxSlides {
			break
		}
	}
	return out
}

func presentationOutlineContent(slides []presentationSlide) string {
	var builder strings.Builder
	for index, slide := range slides {
		if index > 0 {
			builder.WriteString("\n")
		}
		builder.WriteString("### Slide ")
		builder.WriteString(fmt.Sprintf("%d: ", index+1))
		builder.WriteString(slide.Title)
		builder.WriteString("\n\n")
		for _, bullet := range slide.Bullets {
			builder.WriteString("- ")
			builder.WriteString(bullet)
			builder.WriteString("\n")
		}
	}
	return strings.TrimSpace(builder.String())
}

func presentationOutlineTitle(sourceTitle string, sourcePath string) string {
	sourceTitle = strings.TrimSpace(sourceTitle)
	if sourceTitle != "" {
		return "Presentation Outline - " + sourceTitle
	}
	sourcePath = filepath.ToSlash(strings.TrimSpace(sourcePath))
	if sourcePath != "" {
		name := strings.TrimSuffix(filepath.Base(sourcePath), filepath.Ext(sourcePath))
		if strings.TrimSpace(name) != "" {
			return "Presentation Outline - " + name
		}
	}
	return "Presentation Outline"
}

func presentationOutlineSourcePaths(sourcePath string, sourcePaths []string) []string {
	candidates := append([]string{sourcePath}, sourcePaths...)
	seen := map[string]bool{}
	out := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		candidate = filepath.ToSlash(strings.TrimSpace(candidate))
		if candidate == "" || seen[candidate] {
			continue
		}
		seen[candidate] = true
		out = append(out, candidate)
	}
	return out
}

func presentationTrimBullet(value string) string {
	value = strings.Join(strings.Fields(strings.TrimSpace(value)), " ")
	if len(value) <= presentationMaxBulletLength {
		return value
	}
	return strings.TrimSpace(value[:presentationMaxBulletLength-1]) + "..."
}

func countPresentationSlides(content string) int {
	count := 0
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "### Slide ") {
			count++
		}
	}
	return count
}
