package artifacts

import (
	"strings"
	"testing"
)

func TestBuildPresentationOutlineReportCreatesSlidesFromMarkdown(t *testing.T) {
	report := BuildPresentationOutlineReport(
		"",
		".nexusdesk/artifacts/document-sets/report.md",
		"Architecture Notes",
		"document-report",
		"# Architecture Notes\n\n## Goals\n\n- Keep the shell native\n- Preserve source lineage\n\n## Risks\n\nLong-running report work needs job routing.\n",
		[]string{"docs/a.md"},
	)
	if report.Title != "Presentation Outline - Architecture Notes" || report.SourcePath == "" || report.SlideCount != 3 {
		t.Fatalf("unexpected report header: %#v", report)
	}
	for _, expected := range []string{"### Slide 1: Architecture Notes", "Keep the shell native", "### Slide 3: Risks", "Long-running report work"} {
		if !strings.Contains(report.Content, expected) {
			t.Fatalf("outline missing %q:\n%s", expected, report.Content)
		}
	}
}

func TestWritePresentationOutlineReportCreatesMetadataBackedArtifact(t *testing.T) {
	store, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	artifact, err := store.WritePresentationOutlineReport(PresentationOutlineReport{
		Title:       "Presentation Outline - Architecture Notes",
		SourcePath:  ".nexusdesk/artifacts/document-sets/report.md",
		SourceTitle: "Architecture Notes",
		SourceKind:  "document-report",
		SourcePaths: []string{"docs/a.md", "docs/b.md"},
		Content:     "### Slide 1: Goals\n\n- Keep the shell native\n",
		SlideCount:  1,
		GeneratedBy: "test",
	})
	if err != nil {
		t.Fatalf("WritePresentationOutlineReport returned error: %v", err)
	}
	if artifact.Kind != "presentation-outline" || artifact.MetadataPath == "" || len(artifact.SourcePaths) != 3 {
		t.Fatalf("expected metadata-backed presentation outline artifact, got %#v", artifact)
	}
	if !strings.HasPrefix(artifact.RelPath, ".nexusdesk/artifacts/presentations/") {
		t.Fatalf("unexpected artifact path: %q", artifact.RelPath)
	}
	text, err := store.ReadArtifactText(artifact.RelPath)
	if err != nil {
		t.Fatalf("ReadArtifactText returned error: %v", err)
	}
	for _, expected := range []string{"# Presentation Outline - Architecture Notes", "Generated by:** test", "Source artifact:** .nexusdesk/artifacts/document-sets/report.md", "Slides:** 1", "docs/a.md", "### Slide 1: Goals"} {
		if !strings.Contains(text, expected) {
			t.Fatalf("presentation outline missing %q:\n%s", expected, text)
		}
	}
	metadata, err := store.ReadArtifactMetadata(artifact.RelPath)
	if err != nil {
		t.Fatalf("ReadArtifactMetadata returned error: %v", err)
	}
	if metadata.Kind != "presentation-outline" || metadata.Source != ".nexusdesk/artifacts/document-sets/report.md" {
		t.Fatalf("unexpected metadata: %#v", metadata)
	}
	if len(metadata.SourcePaths) != 3 || metadata.SourcePaths[0] != ".nexusdesk/artifacts/document-sets/report.md" {
		t.Fatalf("expected source artifact first in source paths, got %#v", metadata.SourcePaths)
	}
}

func TestWritePresentationOutlineReportRequiresContent(t *testing.T) {
	store, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if _, err := store.WritePresentationOutlineReport(PresentationOutlineReport{Title: "Empty"}); err == nil {
		t.Fatal("expected empty presentation outline to be rejected")
	}
}
