// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentWorkspaces() {
  return window['go']['main']['App']['GetRecentWorkspaces']();
}

export function GetStartupState() {
  return window['go']['main']['App']['GetStartupState']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function RefreshWorkspace() {
  return window['go']['main']['App']['RefreshWorkspace']();
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}
