// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {main} from '../models';
import {artifact} from '../models';
import {llm} from '../models';
import {storage} from '../models';
import {analytics} from '../models';
import {appmeta} from '../models';
import {agenttools} from '../models';
import {dbconnector} from '../models';
import {approval} from '../models';
import {dataset} from '../models';
import {agent} from '../models';

export function AgentSystemPrompt():Promise<string>;

export function ApplyFileCopy(arg1:workspace.FileCopyRequest):Promise<workspace.FileCopyProposal>;

export function ApplyFileDelete(arg1:string):Promise<workspace.FileDeleteProposal>;

export function ApplyFileMove(arg1:workspace.FileMoveRequest):Promise<workspace.FileMoveProposal>;

export function ApplyFileWrite(arg1:workspace.FileWriteRequest):Promise<workspace.FileWriteProposal>;

export function ApplyGitFileAction(arg1:main.GitFileActionRequest):Promise<main.GitFileActionPreview>;

export function ApplyGitHunkAction(arg1:main.GitHunkActionRequest):Promise<main.GitHunkActionPreview>;

export function ArchiveArtifact(arg1:string):Promise<artifact.MarkdownReport>;

export function AskLLM(arg1:string,arg2:string):Promise<llm.ChatResult>;

export function AskLLMContextPack(arg1:string,arg2:Array<string>):Promise<llm.ChatResult>;

export function AskLLMStream(arg1:string,arg2:string,arg3:string):Promise<llm.ChatResult>;

export function AskLLMStreamContextPack(arg1:string,arg2:Array<string>,arg3:string):Promise<llm.ChatResult>;

export function CheckWorkspaceFreshness():Promise<workspace.FreshnessStatus>;

export function ClearChatHistory():Promise<Array<storage.ChatMessage>>;

export function ClearRecentWorkspaces():Promise<Array<storage.RecentWorkspace>>;

export function CompareArtifacts(arg1:string,arg2:string):Promise<artifact.ArtifactComparison>;

export function CreateChatMarkdownArtifact(arg1:artifact.MarkdownArtifactRequest):Promise<artifact.MarkdownReport>;

export function CreateDatasetChartArtifact(arg1:workspace.DatasetChartRequest):Promise<artifact.MarkdownReport>;

export function CreateDatasetQueryArtifact(arg1:string,arg2:string):Promise<artifact.MarkdownReport>;

export function CreateDatasetSQLArtifact(arg1:analytics.SQLQueryRequest):Promise<artifact.MarkdownReport>;

export function CreateDatasetSummaryArtifact(arg1:string):Promise<artifact.MarkdownReport>;

export function CreateMarkdownReport(arg1:string):Promise<artifact.MarkdownReport>;

export function CreateScanReportArtifact():Promise<artifact.MarkdownReport>;

export function DeleteArtifact(arg1:string):Promise<artifact.MarkdownReport>;

export function DeleteConnectorProfile(arg1:string):Promise<void>;

export function EnsureSQLiteMetadataStore():Promise<appmeta.SQLiteStatus>;

export function ExecuteAgentTool(arg1:agenttools.RunRequest):Promise<agenttools.RunRecord>;

export function ExportArtifactLineageJSON():Promise<artifact.MarkdownReport>;

export function GetArtifactLineage():Promise<main.ArtifactLineage>;

export function GetArtifactMetadata(arg1:string):Promise<artifact.ArtifactMetadata>;

export function GetAssistantProfile():Promise<storage.AssistantProfile>;

export function GetChatHistory():Promise<Array<storage.ChatMessage>>;

export function GetGitFileDiff(arg1:string):Promise<main.GitFileDiff>;

export function GetGitStatus():Promise<main.GitStatus>;

export function GetLLMSettings():Promise<storage.LLMSettings>;

export function GetRecentWorkspaces():Promise<Array<storage.RecentWorkspace>>;

export function GetStartupState():Promise<main.StartupState>;

export function ImportArtifactLineageJSON(arg1:string):Promise<main.ArtifactLineageImport>;

export function InspectMetadataStore():Promise<appmeta.MetadataBrowser>;

export function InspectWorkspaceSQLite(arg1:string):Promise<dbconnector.ConnectorMetadata>;

export function ListAgentToolRuns():Promise<Array<agenttools.RunRecord>>;

export function ListAgentTools():Promise<Array<agenttools.Descriptor>>;

export function ListApprovals():Promise<Array<approval.Record>>;

export function ListArtifacts():Promise<Array<artifact.WorkspaceArtifact>>;

export function ListConnectorProfiles():Promise<Array<storage.ConnectorProfile>>;

export function ListDatasetDependencies(arg1:string):Promise<Array<appmeta.DatasetDependency>>;

export function ListDatasetProfiles():Promise<Array<dataset.Profile>>;

export function ListDatasetQueries(arg1:string):Promise<Array<dataset.SavedQuery>>;

export function ListDatasetSQLQueries(arg1:string):Promise<Array<dataset.SavedQuery>>;

export function ListDatasetSQLRuns(arg1:string):Promise<Array<appmeta.SQLRun>>;

export function ListWorkspaceProblems():Promise<workspace.ProblemSummary>;

export function ListWorkspaceTasks():Promise<main.WorkspaceTaskSummary>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceOpenResult>;

export function PreviewAgentTool(arg1:agenttools.RunRequest):Promise<agenttools.RunRecord>;

export function PreviewChatContextPack(arg1:Array<string>):Promise<workspace.ContextPreview>;

export function PreviewDatasetChart(arg1:workspace.DatasetChartRequest):Promise<workspace.DatasetChartResult>;

export function PreviewFileCopy(arg1:workspace.FileCopyRequest):Promise<workspace.FileCopyProposal>;

export function PreviewFileDelete(arg1:string):Promise<workspace.FileDeleteProposal>;

export function PreviewFileMove(arg1:workspace.FileMoveRequest):Promise<workspace.FileMoveProposal>;

export function PreviewFileWrite(arg1:workspace.FileWriteRequest):Promise<workspace.FileWriteProposal>;

export function PreviewGitFileAction(arg1:main.GitFileActionRequest):Promise<main.GitFileActionPreview>;

export function PreviewGitHunkAction(arg1:main.GitHunkActionRequest):Promise<main.GitHunkActionPreview>;

export function ProfileDataset(arg1:string):Promise<dataset.Profile>;

export function QueryDataset(arg1:string,arg2:string):Promise<workspace.DatasetQueryResult>;

export function QueryDatasetSQL(arg1:analytics.SQLQueryRequest):Promise<analytics.SQLQueryResult>;

export function QueryWorkspaceSQLite(arg1:dbconnector.SQLiteQueryRequest):Promise<dbconnector.SQLiteQueryResult>;

export function ReadWorkspaceFile(arg1:string):Promise<workspace.FilePreview>;

export function RebuildDatasetDependency(arg1:string):Promise<artifact.MarkdownReport>;

export function RefreshStaleContext(arg1:Array<string>):Promise<main.StaleContextRefresh>;

export function RefreshWorkspace():Promise<main.WorkspaceOpenResult>;

export function RemoveRecentWorkspace(arg1:string):Promise<Array<storage.RecentWorkspace>>;

export function RunAgent(arg1:agent.RunRequest):Promise<agent.RunResult>;

export function RunWorkspaceTask(arg1:main.WorkspaceTaskRunRequest):Promise<main.WorkspaceTaskRunResult>;

export function SaveAssistantProfile(arg1:storage.AssistantProfile):Promise<storage.AssistantProfile>;

export function SaveConnectorProfile(arg1:storage.ConnectorProfile):Promise<storage.ConnectorProfile>;

export function SaveDatasetQuery(arg1:string,arg2:string,arg3:string):Promise<dataset.SavedQuery>;

export function SaveDatasetSQLQuery(arg1:string,arg2:string,arg3:string):Promise<dataset.SavedQuery>;

export function SaveLLMSettings(arg1:storage.LLMSettings):Promise<storage.LLMSettings>;

export function SearchMetadata(arg1:string):Promise<Array<appmeta.MetadataSearchResult>>;

export function SearchWorkspace(arg1:string):Promise<Array<workspace.SearchResult>>;

export function SearchWorkspaceAdvanced(arg1:main.WorkspaceSearchRequest):Promise<Array<workspace.SearchResult>>;

export function SelectWorkspace():Promise<main.WorkspaceOpenResult>;

export function TestLLMConnection(arg1:storage.LLMSettings):Promise<llm.ProbeResult>;
