// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {llm} from '../models';
import {storage} from '../models';
import {artifact} from '../models';
import {main} from '../models';
import {dataset} from '../models';

export function ApplyFileDelete(arg1:string):Promise<workspace.FileDeleteProposal>;

export function ApplyFileWrite(arg1:workspace.FileWriteRequest):Promise<workspace.FileWriteProposal>;

export function AskLLM(arg1:string,arg2:string):Promise<llm.ChatResult>;

export function AskLLMContextPack(arg1:string,arg2:Array<string>):Promise<llm.ChatResult>;

export function AskLLMStream(arg1:string,arg2:string,arg3:string):Promise<llm.ChatResult>;

export function AskLLMStreamContextPack(arg1:string,arg2:Array<string>,arg3:string):Promise<llm.ChatResult>;

export function ClearChatHistory():Promise<Array<storage.ChatMessage>>;

export function ClearRecentWorkspaces():Promise<Array<storage.RecentWorkspace>>;

export function CreateChatMarkdownArtifact(arg1:artifact.MarkdownArtifactRequest):Promise<artifact.MarkdownReport>;

export function CreateMarkdownReport(arg1:string):Promise<artifact.MarkdownReport>;

export function GetChatHistory():Promise<Array<storage.ChatMessage>>;

export function GetLLMSettings():Promise<storage.LLMSettings>;

export function GetRecentWorkspaces():Promise<Array<storage.RecentWorkspace>>;

export function GetStartupState():Promise<main.StartupState>;

export function ListArtifacts():Promise<Array<artifact.WorkspaceArtifact>>;

export function ListDatasetProfiles():Promise<Array<dataset.Profile>>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceOpenResult>;

export function PreviewChatContextPack(arg1:Array<string>):Promise<workspace.ContextPreview>;

export function PreviewFileDelete(arg1:string):Promise<workspace.FileDeleteProposal>;

export function PreviewFileWrite(arg1:workspace.FileWriteRequest):Promise<workspace.FileWriteProposal>;

export function ProfileDataset(arg1:string):Promise<dataset.Profile>;

export function QueryDataset(arg1:string,arg2:string):Promise<workspace.DatasetQueryResult>;

export function ReadWorkspaceFile(arg1:string):Promise<workspace.FilePreview>;

export function RefreshWorkspace():Promise<main.WorkspaceOpenResult>;

export function RemoveRecentWorkspace(arg1:string):Promise<Array<storage.RecentWorkspace>>;

export function SaveLLMSettings(arg1:storage.LLMSettings):Promise<storage.LLMSettings>;

export function SearchWorkspace(arg1:string):Promise<Array<workspace.SearchResult>>;

export function SelectWorkspace():Promise<main.WorkspaceOpenResult>;

export function TestLLMConnection(arg1:storage.LLMSettings):Promise<llm.ProbeResult>;
