// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStartupState():Promise<main.StartupState>;

export function SelectWorkspace():Promise<main.WorkspaceOpenResult>;
