// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupState() {
  return window['go']['main']['App']['GetStartupState']();
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}
