// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentSystemPrompt() {
  return window['go']['main']['App']['AgentSystemPrompt']();
}

export function ApplyFileCopy(arg1) {
  return window['go']['main']['App']['ApplyFileCopy'](arg1);
}

export function ApplyFileDelete(arg1) {
  return window['go']['main']['App']['ApplyFileDelete'](arg1);
}

export function ApplyFileMove(arg1) {
  return window['go']['main']['App']['ApplyFileMove'](arg1);
}

export function ApplyFileWrite(arg1) {
  return window['go']['main']['App']['ApplyFileWrite'](arg1);
}

export function ApplyGitFileAction(arg1) {
  return window['go']['main']['App']['ApplyGitFileAction'](arg1);
}

export function ApplyGitHunkAction(arg1) {
  return window['go']['main']['App']['ApplyGitHunkAction'](arg1);
}

export function ArchiveArtifact(arg1) {
  return window['go']['main']['App']['ArchiveArtifact'](arg1);
}

export function AskLLM(arg1, arg2) {
  return window['go']['main']['App']['AskLLM'](arg1, arg2);
}

export function AskLLMContextPack(arg1, arg2) {
  return window['go']['main']['App']['AskLLMContextPack'](arg1, arg2);
}

export function AskLLMStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['AskLLMStream'](arg1, arg2, arg3);
}

export function AskLLMStreamContextPack(arg1, arg2, arg3) {
  return window['go']['main']['App']['AskLLMStreamContextPack'](arg1, arg2, arg3);
}

export function CheckWorkspaceFreshness() {
  return window['go']['main']['App']['CheckWorkspaceFreshness']();
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function ClearRecentWorkspaces() {
  return window['go']['main']['App']['ClearRecentWorkspaces']();
}

export function CompareArtifacts(arg1, arg2) {
  return window['go']['main']['App']['CompareArtifacts'](arg1, arg2);
}

export function CreateChatMarkdownArtifact(arg1) {
  return window['go']['main']['App']['CreateChatMarkdownArtifact'](arg1);
}

export function CreateDatasetChartArtifact(arg1) {
  return window['go']['main']['App']['CreateDatasetChartArtifact'](arg1);
}

export function CreateDatasetQueryArtifact(arg1, arg2) {
  return window['go']['main']['App']['CreateDatasetQueryArtifact'](arg1, arg2);
}

export function CreateDatasetSQLArtifact(arg1) {
  return window['go']['main']['App']['CreateDatasetSQLArtifact'](arg1);
}

export function CreateDatasetSummaryArtifact(arg1) {
  return window['go']['main']['App']['CreateDatasetSummaryArtifact'](arg1);
}

export function CreateMarkdownReport(arg1) {
  return window['go']['main']['App']['CreateMarkdownReport'](arg1);
}

export function CreateScanReportArtifact() {
  return window['go']['main']['App']['CreateScanReportArtifact']();
}

export function DeleteArtifact(arg1) {
  return window['go']['main']['App']['DeleteArtifact'](arg1);
}

export function EnsureSQLiteMetadataStore() {
  return window['go']['main']['App']['EnsureSQLiteMetadataStore']();
}

export function ExecuteAgentTool(arg1) {
  return window['go']['main']['App']['ExecuteAgentTool'](arg1);
}

export function ExportArtifactLineageJSON() {
  return window['go']['main']['App']['ExportArtifactLineageJSON']();
}

export function GetArtifactLineage() {
  return window['go']['main']['App']['GetArtifactLineage']();
}

export function GetArtifactMetadata(arg1) {
  return window['go']['main']['App']['GetArtifactMetadata'](arg1);
}

export function GetAssistantProfile() {
  return window['go']['main']['App']['GetAssistantProfile']();
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetGitFileDiff(arg1) {
  return window['go']['main']['App']['GetGitFileDiff'](arg1);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetLLMSettings() {
  return window['go']['main']['App']['GetLLMSettings']();
}

export function GetRecentWorkspaces() {
  return window['go']['main']['App']['GetRecentWorkspaces']();
}

export function GetStartupState() {
  return window['go']['main']['App']['GetStartupState']();
}

export function ImportArtifactLineageJSON(arg1) {
  return window['go']['main']['App']['ImportArtifactLineageJSON'](arg1);
}

export function InspectMetadataStore() {
  return window['go']['main']['App']['InspectMetadataStore']();
}

export function ListAgentToolRuns() {
  return window['go']['main']['App']['ListAgentToolRuns']();
}

export function ListAgentTools() {
  return window['go']['main']['App']['ListAgentTools']();
}

export function ListApprovals() {
  return window['go']['main']['App']['ListApprovals']();
}

export function ListArtifacts() {
  return window['go']['main']['App']['ListArtifacts']();
}

export function ListDatasetDependencies(arg1) {
  return window['go']['main']['App']['ListDatasetDependencies'](arg1);
}

export function ListDatasetProfiles() {
  return window['go']['main']['App']['ListDatasetProfiles']();
}

export function ListDatasetQueries(arg1) {
  return window['go']['main']['App']['ListDatasetQueries'](arg1);
}

export function ListDatasetSQLQueries(arg1) {
  return window['go']['main']['App']['ListDatasetSQLQueries'](arg1);
}

export function ListDatasetSQLRuns(arg1) {
  return window['go']['main']['App']['ListDatasetSQLRuns'](arg1);
}

export function ListWorkspaceTasks() {
  return window['go']['main']['App']['ListWorkspaceTasks']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function PreviewAgentTool(arg1) {
  return window['go']['main']['App']['PreviewAgentTool'](arg1);
}

export function PreviewChatContextPack(arg1) {
  return window['go']['main']['App']['PreviewChatContextPack'](arg1);
}

export function PreviewDatasetChart(arg1) {
  return window['go']['main']['App']['PreviewDatasetChart'](arg1);
}

export function PreviewFileCopy(arg1) {
  return window['go']['main']['App']['PreviewFileCopy'](arg1);
}

export function PreviewFileDelete(arg1) {
  return window['go']['main']['App']['PreviewFileDelete'](arg1);
}

export function PreviewFileMove(arg1) {
  return window['go']['main']['App']['PreviewFileMove'](arg1);
}

export function PreviewFileWrite(arg1) {
  return window['go']['main']['App']['PreviewFileWrite'](arg1);
}

export function PreviewGitFileAction(arg1) {
  return window['go']['main']['App']['PreviewGitFileAction'](arg1);
}

export function PreviewGitHunkAction(arg1) {
  return window['go']['main']['App']['PreviewGitHunkAction'](arg1);
}

export function ProfileDataset(arg1) {
  return window['go']['main']['App']['ProfileDataset'](arg1);
}

export function QueryDataset(arg1, arg2) {
  return window['go']['main']['App']['QueryDataset'](arg1, arg2);
}

export function QueryDatasetSQL(arg1) {
  return window['go']['main']['App']['QueryDatasetSQL'](arg1);
}

export function QueryWorkspaceSQLite(arg1) {
  return window['go']['main']['App']['QueryWorkspaceSQLite'](arg1);
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1);
}

export function RebuildDatasetDependency(arg1) {
  return window['go']['main']['App']['RebuildDatasetDependency'](arg1);
}

export function RefreshStaleContext(arg1) {
  return window['go']['main']['App']['RefreshStaleContext'](arg1);
}

export function RefreshWorkspace() {
  return window['go']['main']['App']['RefreshWorkspace']();
}

export function RemoveRecentWorkspace(arg1) {
  return window['go']['main']['App']['RemoveRecentWorkspace'](arg1);
}

export function RunAgent(arg1) {
  return window['go']['main']['App']['RunAgent'](arg1);
}

export function SaveAssistantProfile(arg1) {
  return window['go']['main']['App']['SaveAssistantProfile'](arg1);
}

export function SaveDatasetQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDatasetQuery'](arg1, arg2, arg3);
}

export function SaveDatasetSQLQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDatasetSQLQuery'](arg1, arg2, arg3);
}

export function SaveLLMSettings(arg1) {
  return window['go']['main']['App']['SaveLLMSettings'](arg1);
}

export function SearchMetadata(arg1) {
  return window['go']['main']['App']['SearchMetadata'](arg1);
}

export function SearchWorkspace(arg1) {
  return window['go']['main']['App']['SearchWorkspace'](arg1);
}

export function SearchWorkspaceAdvanced(arg1) {
  return window['go']['main']['App']['SearchWorkspaceAdvanced'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}
